__title__ = 'Flask-DJ'
__description__ = 'Django (mvc) structure for your Flask project.'
__url__ = 'https://flask-dj.readthedocs.io/en/latest/'
__version__ = '0.0.10'
__author__ = 'Alexandrov Roman'
__author_email__ = 'flask-dj.feedback@yandex.com'
__license__ = 'MIT License'
__keywords__ = 'mvc django flask structure'
